# Generated by Django 5.2.8 on 2025-12-02 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statsperiod_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='gifts_rr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='gifts_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='msg_rr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='msg_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='photos_rr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpidaily',
            name='photos_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statsperiod',
            name='penalites',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='statsperiod',
            name='responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
