# Generated by Django 5.2.8 on 2025-12-02 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('moment', models.CharField(choices=[('debut', 'Début de capture'), ('fin', 'Fin de capture')], max_length=10)),
                ('msg_sent', models.IntegerField()),
                ('msg_rr', models.IntegerField()),
                ('photos_sent', models.IntegerField()),
                ('photos_rr', models.IntegerField()),
                ('gifts_sent', models.IntegerField()),
                ('gifts_rr', models.IntegerField()),
                ('speed_rr', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI Journalier',
                'verbose_name_plural': 'KPIs Journaliers',
                'db_table': 'kpi_daily',
                'ordering': ['-date', 'moment'],
                'unique_together': {('date', 'moment')},
            },
        ),
        migrations.CreateModel(
            name='StatsPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(choices=[('debut', 'Début de capture'), ('fin', 'Fin de capture')], max_length=10)),
                ('period_type', models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois')], max_length=10)),
                ('responses', models.IntegerField(default=0)),
                ('kpi_effect', models.IntegerField(default=0)),
                ('extra_benefits', models.IntegerField(default=0)),
                ('penalites', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi_daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_periods', to='stats.kpidaily')),
            ],
            options={
                'verbose_name': 'Statistique Périodique',
                'verbose_name_plural': 'Statistiques Périodiques',
                'db_table': 'stats_period',
                'ordering': ['-kpi_daily__date'],
                'indexes': [models.Index(fields=['period_type'], name='stats_perio_period__bc13e0_idx'), models.Index(fields=['kpi_daily', 'period_type'], name='stats_perio_kpi_dai_c73e80_idx')],
                'unique_together': {('kpi_daily', 'moment')},
            },
        ),
    ]
