# Generated by Django 5.2.8 on 2025-12-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statsperiod',
            unique_together={('kpi_daily', 'moment', 'period_type')},
        ),
    ]
