# Generated by Django 5.2.8 on 2025-12-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_statsperiod_updated_at_alter_kpidaily_gifts_rr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidaily',
            name='image_kpi',
            field=models.ImageField(blank=True, null=True, upload_to='kpi_images/'),
        ),
        migrations.AddField(
            model_name='statsperiod',
            name='image_stats',
            field=models.ImageField(blank=True, null=True, upload_to='stats_images/'),
        ),
    ]
