# Generated by Django 5.2.8 on 2025-12-02 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_kpidaily_image_kpi_statsperiod_image_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidaily',
            name='image_kpi',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_kpi'),
        ),
        migrations.AlterField(
            model_name='statsperiod',
            name='image_stats',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image_stats'),
        ),
    ]
