# Generated by Django 5.2.8 on 2025-12-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_kpidaily_image_kpi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidaily',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
